easy_admin:
  entities:
    - App\Entity\Categorie
    - App\Entity\Produit
    - App\Entity\User
    # design:
    # # # brand_color: '#1ABC9C'
    #   menu:
    #     - label: 'ECommerce'
    #       icon: 'cart'
    # #       children:
          
    #         # - {entity: 'Produit', icon: 'folder-open', label: 'Produits'}
    #         # - {entity: 'Categorie', icon: 'folder-open', label: 'Catégories'}
    #     - label: 'Accès'
    #       icon: 'user'
    #       children:
    #         # - {entity: 'User', icon: 'folder-open', label: 'Utilisateurs'}

# imports:
#       - {resource: admin/}
    # entities:
        # Produit:
        #     class: - App\Entity\Produit
        #     form:
        #         fields:
        #             - {property: 'id'}
        #             - {property: 'nom'}
        #             - {property: 'description'}
        #             - {property: 'prix'}
        #             - {property: 'image'}
        #             - {property: 'categorie_id'}
        #             - {property: 'user_id'}
        #             - {property: 'commentaires'}
        # Categorie:
        #       class: - App\Entity\Categorie
        #       form:
        #           fields:
        #               - {property: 'id'}
        #               - {property: 'titre'}
        #               - {property: 'produits'}
        # User:
        #   class: - App\Entity\User
        #   form:
        #       fields:
        #           - {property: 'id'}
        #           - {property: 'email'}
        #           - {property: 'password'}
        #           - {property: 'username'}
        #           - {property: 'produits'}
        #           - {property: 'commentaires'}